# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MLCast Community intake catalog - datasets for ML nowcasting
author: The MLCast Community
#logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  # ensure that cell execution doesn't timeout (this is necessary because
  # creating some of the figures takes a long time)
  # see https://github.com/jupyter-book/jupyter-book/issues/948 and
  # https://jupyterbook.org/en/stable/content/execute.html#setting-execution-timeout
  # for details
  timeout: -1
  # ensure that that if any cell fails, the entire notebook is marked as failed
  # so that we can pick this up in the CI
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
  #- references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/mlcast-community/mlcast-datasets/
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  config:
    copyright: ""
  local_extensions:
    copyright_year_sphinxext: utils
  extra_extensions:
    - sphinxcontrib.mermaid
